### ISSUE TITLE
Compile applet without debug info

### ISSUE THREAD

**Issue by beothorn** [beothorn/libreSubs#46]
Compile Applet without debug info, so it gets smaller. Maybe generate a new applet without the background image on the drop text area.

**Comment by kalecser** [comment]
-rw-r--r-- 1 kalecser kalecser  51K 2011-02-13 14:57 libreSubsApplet-0.0.1-SNAPSHOT.jar
-rw-r--r-- 1 kalecser kalecser  45K 2011-02-13 16:31 libreSubsApplet-0.0.1-SNAPSHOT.jar
